apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "minio",
      "access_key": "$MINIO_ROOT_USER",
      "endpoint": "minio.prow.svc.cluster.local",
      "insecure": true,
      "s3_force_path_style": true,
      "secret_key": "$MINIO_ROOT_PASSWORD"
    }
