apiVersion: v1
kind: Secret
metadata:
  name: github-token
data:
  cert: $GITHUB_TOKEN
stringData:
  appid: |
    $GITHUB_APP_ID
---
apiVersion: v1
kind: Secret
metadata:
  name: hmac-token
stringData:
  # Generate via `openssl rand -hex 20`. This is the secret used in the GitHub webhook configuration
  hmac: $HMAC_TOKEN
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-root-creds
stringData:
  user: "$MINIO_ROOT_USER"
  password: "$MINIO_ROOT_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "minio",
      "access_key": "$MINIO_ROOT_USER",
      "endpoint": "minio.prow.svc.cluster.local",
      "insecure": true,
      "s3_force_path_style": true,
      "secret_key": "$MINIO_ROOT_PASSWORD"
    }
